{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 02 Census Data Collection\n",
    "\n",
    "**Purpose**: Download and process IBGE 2022 Census data for Amazon municipalities\n",
    "\n",
    "**Time Required**: 2-3 hours\n",
    "\n",
    "**Data Sources**: \n",
    "- IBGE 2022 Population Census (censobr package)\n",
    "- Municipal boundaries (geobr package)\n",
    "\n",
    "**Deliverables**: \n",
    "- Population data by municipality\n",
    "- Household characteristics data\n",
    "- Municipal boundary shapefiles\n",
    "- Data quality report\n",
    "\n",
    "---"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 1: Load Configuration and Libraries"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load essential libraries\n",
    "library(censobr)\n",
    "library(geobr)\n",
    "library(sf)\n",
    "library(dplyr)\n",
    "library(readr)\n",
    "library(ggplot2)\n",
    "library(leaflet)\n",
    "library(DT)\n",
    "\n",
    "# Load project configuration\n",
    "if (file.exists(\"data/project_config.rds\")) {\n",
    "  config <- readRDS(\"data/project_config.rds\")\n",
    "  amazon_states <- config$amazon_states\n",
    "  amazon_states_full <- config$amazon_states_full\n",
    "  PROJECT_CONFIG <- config$project_config\n",
    "  \n",
    "  cat(\"✅ Configuration loaded successfully\\n\")\n",
    "  cat(\"📍 Working with\", length(amazon_states), \"Amazon states\\n\")\n",
    "} else {\n",
    "  cat(\"⚠️ Configuration not found. Please run 01_environment_setup.ipynb first.\\n\")\n",
    "  stop(\"Missing configuration file\")\n",
    "}\n",
    "\n",
    "# Load helper functions\n",
    "standardize_muni_code <- function(code) {\n",
    "  sprintf(\"%07d\", as.numeric(code))\n",
    "}\n",
    "\n",
    "save_data_with_metadata <- function(data, filename, description = \"\") {\n",
    "  write_csv(data, filename)\n",
    "  metadata <- list(\n",
    "    filename = basename(filename),\n",
    "    created = Sys.time(),\n",
    "    rows = nrow(data),\n",
    "    columns = ncol(data),\n",
    "    description = description\n",
    "  )\n",
    "  metadata_file <- paste0(tools::file_path_sans_ext(filename), \"_metadata.json\")\n",
    "  write(jsonlite::toJSON(metadata, pretty = TRUE), metadata_file)\n",
    "  cat(\"💾 Saved:\", filename, \"(\", nrow(data), \"rows)\\n\")\n",
    "}"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 2: Explore Available Census Data\n",
    "\n",
    "First, let's see what census data is available for 2022."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Check what census tables are available\n",
    "cat(\"🔍 Exploring available 2022 census data...\\n\")\n",
    "\n",
    "tryCatch({\n",
    "  # List available census tables\n",
    "  available_tables <- list_census_tables(year = 2022)\n",
    "  \n",
    "  cat(\"📊 Found\", nrow(available_tables), \"available census tables\\n\\n\")\n",
    "  \n",
    "  # Show the first few tables\n",
    "  cat(\"First 10 available tables:\\n\")\n",
    "  print(head(available_tables, 10))\n",
    "  \n",
    "  # Save the full list for reference\n",
    "  save_data_with_metadata(\n",
    "    available_tables, \n",
    "    \"data/raw/census/available_census_tables_2022.csv\",\n",
    "    \"Complete list of available IBGE 2022 census tables\"\n",
    "  )\n",
    "  \n",
    "}, error = function(e) {\n",
    "  cat(\"⚠️ Could not retrieve table list. Error:\", e$message, \"\\n\")\n",
    "  cat(\"Proceeding with standard data download...\\n\")\n",
    "})"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 3: Download Population Data\n",
    "\n",
    "Download basic population statistics for all Amazon municipalities."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Download population data\n",
    "cat(\"👥 Downloading population data for Amazon states...\\n\")\n",
    "\n",
    "tryCatch({\n",
    "  # Download population data by municipality\n",
    "  pop_data <- read_population(\n",
    "    year = PROJECT_CONFIG$census_year,\n",
    "    columns = c(\n",
    "      \"code_muni\",      # Municipality code\n",
    "      \"name_muni\",      # Municipality name\n",
    "      \"abbrev_state\",   # State abbreviation\n",
    "      \"name_state\",     # State name\n",
    "      \"population\",     # Total population\n",
    "      \"pop_male\",       # Male population\n",
    "      \"pop_female\"      # Female population\n",
    "    ),\n",
    "    add_labels = TRUE,\n",
    "    as_data_frame = TRUE\n",
    "  )\n",
    "  \n",
    "  cat(\"✅ Downloaded population data for\", nrow(pop_data), \"municipalities\\n\")\n",
    "  \n",
    "  # Filter for Amazon states only\n",
    "  amazon_pop <- pop_data %>% \n",
    "    filter(abbrev_state %in% amazon_states) %>%\n",
    "    mutate(code_muni = standardize_muni_code(code_muni)) %>%\n",
    "    arrange(abbrev_state, name_muni)\n",
    "  \n",
    "  cat(\"🌿 Filtered to\", nrow(amazon_pop), \"Amazon municipalities\\n\")\n",
    "  \n",
    "  # Add calculated columns\n",
    "  amazon_pop <- amazon_pop %>%\n",
    "    mutate(\n",
    "      pop_density_calculated = population / 1000,  # We'll calculate proper density later with area\n",
    "      male_percentage = (pop_male / population) * 100,\n",
    "      female_percentage = (pop_female / population) * 100\n",
    "    )\n",
    "  \n",
    "  # Display summary by state\n",
    "  state_summary <- amazon_pop %>%\n",
    "    group_by(abbrev_state, name_state) %>%\n",
    "    summarise(\n",
    "      municipalities = n(),\n",
    "      total_population = sum(population, na.rm = TRUE),\n",
    "      avg_population = round(mean(population, na.rm = TRUE)),\n",
    "      .groups = \"drop\"\n",
    "    ) %>%\n",
    "    arrange(desc(total_population))\n",
    "  \n",
    "  cat(\"\\n📊 Population summary by state:\\n\")\n",
    "  print(state_summary)\n",
    "  \n",
    "  # Save population data\n",
    "  save_data_with_metadata(\n",
    "    amazon_pop, \n",
    "    \"data/raw/census/amazon_population_2022.csv\",\n",
    "    \"Population data for Amazon municipalities from 2022 IBGE Census\"\n",
    "  )\n",
    "  \n",
    "  # Save state summary\n",
    "  save_data_with_metadata(\n",
    "    state_summary,\n",
    "    \"data/raw/census/amazon_states_population_summary.csv\",\n",
    "    \"Population summary by Amazon state\"\n",
    "  )\n",
    "  \n",
    "}, error = function(e) {\n",
    "  cat(\"❌ Error downloading population data:\", e$message, \"\\n\")\n",
    "  cat(\"This might be due to network issues or API limits. Try again later.\\n\")\n",
    "})"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 4: Download Household Characteristics\n",
    "\n",
    "Download data about housing conditions and infrastructure access."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Download household characteristics data\n",
    "cat(\"🏠 Downloading household characteristics data...\\n\")\n",
    "\n",
    "tryCatch({\n",
    "  # Download household data\n",
    "  households_data <- read_households(\n",
    "    year = PROJECT_CONFIG$census_year,\n",
    "    columns = c(\n",
    "      \"code_muni\",              # Municipality code\n",
    "      \"name_muni\",              # Municipality name  \n",
    "      \"abbrev_state\",           # State abbreviation\n",
    "      \"households_total\",       # Total households\n",
    "      \"households_water_supply\", # Access to water supply\n",
    "      \"households_sewage\",      # Sewage access\n",
    "      \"households_electricity\"   # Electricity access\n",
    "    ),\n",
    "    add_labels = TRUE,\n",
    "    as_data_frame = TRUE\n",
    "  )\n",
    "  \n",
    "  cat(\"✅ Downloaded household data for\", nrow(households_data), \"municipalities\\n\")\n",
    "  \n",
    "  # Filter for Amazon states\n",
    "  amazon_households <- households_data %>% \n",
    "    filter(abbrev_state %in% amazon_states) %>%\n",
    "    mutate(code_muni = standardize_muni_code(code_muni)) %>%\n",
    "    arrange(abbrev_state, name_muni)\n",
    "  \n",
    "  # Add calculated percentages\n",
    "  amazon_households <- amazon_households %>%\n",
    "    mutate(\n",
    "      water_access_pct = (households_water_supply / households_total) * 100,\n",
    "      sewage_access_pct = (households_sewage / households_total) * 100,\n",
    "      electricity_access_pct = (households_electricity / households_total) * 100\n",
    "    )\n",
    "  \n",
    "  cat(\"🌿 Processed household data for\", nrow(amazon_households), \"Amazon municipalities\\n\")\n",
    "  \n",
    "  # Calculate infrastructure summary\n",
    "  infra_summary <- amazon_households %>%\n",
    "    summarise(\n",
    "      avg_water_access = round(mean(water_access_pct, na.rm = TRUE), 1),\n",
    "      avg_sewage_access = round(mean(sewage_access_pct, na.rm = TRUE), 1),\n",
    "      avg_electricity_access = round(mean(electricity_access_pct, na.rm = TRUE), 1),\n",
    "      municipalities_count = n()\n",
    "    )\n",
    "  \n",
    "  cat(\"\\n📊 Infrastructure access summary (Amazon region):\\n\")\n",
    "  cat(\"   Water access:\", infra_summary$avg_water_access, \"%\\n\")\n",
    "  cat(\"   Sewage access:\", infra_summary$avg_sewage_access, \"%\\n\")\n",
    "  cat(\"   Electricity access:\", infra_summary$avg_electricity_access, \"%\\n\")\n",
    "  \n",
    "  # Save household data\n",
    "  save_data_with_metadata(\n",
    "    amazon_households, \n",
    "    \"data/raw/census/amazon_households_2022.csv\",\n",
    "    \"Household characteristics for Amazon municipalities from 2022 IBGE Census\"\n",
    "  )\n",
    "  \n",
    "}, error = function(e) {\n",
    "  cat(\"❌ Error downloading household data:\", e$message, \"\\n\")\n",
    "  cat(\"Continuing with available data...\\n\")\n",
    "})"
