{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 03 Trajetorias Dataset Collection\n",
    "\n",
    "**Purpose**: Download and process the Trajetorias dataset - environmental, epidemiological, and economic indicators for Brazilian Legal Amazon municipalities\n",
    "\n",
    "**Time Required**: 1-2 hours\n",
    "\n",
    "**Data Source**: Zenodo repository (DOI: 10.5281/zenodo.7098053)\n",
    "\n",
    "**Deliverables**: \n",
    "- Multidimensional Poverty Index (MPI) data\n",
    "- Vector-borne disease incidence data\n",
    "- Environmental indicators (deforestation, land use)\n",
    "- Population and socioeconomic indicators\n",
    "\n",
    "---"
   ]
  },\n  {\n   \"cell_type\": \"markdown\",\n   \"metadata\": {},\n   \"source\": [\n    \"## Step 8: Create Data Summary Table\\n\",\n    \"\\n\",\n    \"Generate an interactive table showing key variables and their availability.\"\n   ]\n  },\n  {\n   \"cell_type\": \"code\",\n   \"execution_count\": null,\n   \"metadata\": {},\n   \"outputs\": [],\n   \"source\": [\n    \"# Create comprehensive data summary\\n\",\n    \"cat(\\\"📋 Creating data summary table...\\\\n\\\")\\n\",\n    \"\\n\",\n    \"# Combine all key indicators into summary\\n\",\n    \"if (length(key_indicators) > 0) {\\n\",\n    \"  \\n\",\n    \"  summary_table <- data.frame()\\n\",\n    \"  \\n\",\n    \"  for (component in names(key_indicators)) {\\n\",\n    \"    data <- key_indicators[[component]]\\n\",\n    \"    \\n\",\n    \"    if (!is.null(data) && nrow(data) > 0) {\\n\",\n    \"      # Get variable summary\\n\",\n    \"      exclude_cols <- c(\\\"code_muni\\\", \\\"year\\\", \\\"abbrev_state\\\", \\\"name_muni\\\")\\n\",\n    \"      vars_to_summarize <- names(data)[!names(data) %in% exclude_cols]\\n\",\n    \"      \\n\",\n    \"      for (var in vars_to_summarize) {\\n\",\n    \"        var_summary <- data.frame(\\n\",\n    \"          Component = component,\\n\",\n    \"          Variable = var,\\n\",\n    \"          Type = class(data[[var]])[1],\\n\",\n    \"          Missing_Count = sum(is.na(data[[var]])),\\n\",\n    \"          Missing_Percent = round((sum(is.na(data[[var]])) / nrow(data)) * 100, 1),\\n\",\n    \"          Non_Missing_Count = sum(!is.na(data[[var]])),\\n\",\n    \"          stringsAsFactors = FALSE\\n\",\n    \"        )\\n\",\n    \"        \\n\",\n    \"        # Add descriptive statistics for numeric variables\\n\",\n    \"        if (is.numeric(data[[var]])) {\\n\",\n    \"          var_summary$Mean = round(mean(data[[var]], na.rm = TRUE), 2)\\n\",\n    \"          var_summary$Median = round(median(data[[var]], na.rm = TRUE), 2)\\n\",\n    \"          var_summary$Min = round(min(data[[var]], na.rm = TRUE), 2)\\n\",\n    \"          var_summary$Max = round(max(data[[var]], na.rm = TRUE), 2)\\n\",\n    \"        } else {\\n\",\n    \"          var_summary$Mean = NA\\n\",\n    \"          var_summary$Median = NA\\n\",\n    \"          var_summary$Min = NA\\n\",\n    \"          var_summary$Max = NA\\n\",\n    \"        }\\n\",\n    \"        \\n\",\n    \"        summary_table <- rbind(summary_table, var_summary)\\n\",\n    \"      }\\n\",\n    \"    }\\n\",\n    \"  }\\n\",\n    \"  \\n\",\n    \"  if (nrow(summary_table) > 0) {\\n\",\n    \"    # Display interactive table\\n\",\n    \"    cat(\\\"📊 Variable summary table (first 20 rows):\\\\n\\\")\\n\",\n    \"    \\n\",\n    \"    # Show first 20 rows\\n\",\n    \"    display_table <- head(summary_table, 20)\\n\",\n    \"    \\n\",\n    \"    # Create DT table if available, otherwise print\\n\",\n    \"    if (require(\\\"DT\\\", quietly = TRUE)) {\\n\",\n    \"      dt_table <- DT::datatable(\\n\",\n    \"        display_table,\\n\",\n    \"        options = list(\\n\",\n    \"          scrollX = TRUE,\\n\",\n    \"          pageLength = 10,\\n\",\n    \"          searchHighlight = TRUE\\n\",\n    \"        ),\\n\",\n    \"        caption = \\\"Trajetorias Dataset Variable Summary\\\"\\n\",\n    \"      )\\n\",\n    \"      \\n\",\n    \"      print(dt_table)\\n\",\n    \"    } else {\\n\",\n    \"      print(knitr::kable(display_table, caption = \\\"Variable Summary\\\"))\\n\",\n    \"    }\\n\",\n    \"    \\n\",\n    \"    # Save complete summary\\n\",\n    \"    save_data_with_metadata(\\n\",\n    \"      summary_table,\\n\",\n    \"      \\\"outputs/tables/trajetorias_variable_summary.csv\\\",\\n\",\n    \"      \\\"Complete variable summary for Trajetorias dataset\\\"\\n\",\n    \"    )\\n\",\n    \"    \\n\",\n    \"    # Summary statistics by component\\n\",\n    \"    component_summary <- summary_table %>%\\n\",\n    \"      group_by(Component) %>%\\n\",\n    \"      summarise(\\n\",\n    \"        Total_Variables = n(),\\n\",\n    \"        Numeric_Variables = sum(Type %in% c(\\\"numeric\\\", \\\"integer\\\")),\\n\",\n    \"        Avg_Missing_Percent = round(mean(Missing_Percent, na.rm = TRUE), 1),\\n\",\n    \"        Variables_Complete = sum(Missing_Percent == 0),\\n\",\n    \"        .groups = \\\"drop\\\"\\n\",\n    \"      )\\n\",\n    \"    \\n\",\n    \"    cat(\\\"\\\\n📊 Summary by component:\\\\n\\\")\\n\",\n    \"    print(component_summary)\\n\",\n    \"    \\n\",\n    \"  } else {\\n\",\n    \"    cat(\\\"⚠️ No variables found for summary table\\\\n\\\")\\n\",\n    \"  }\\n\",\n    \"  \\n\",\n    \"} else {\\n\",\n    \"  cat(\\\"⚠️ No key indicators available for summary\\\\n\\\")\\n\",\n    \"}\"\n   ]\n  },\n  {\n   \"cell_type\": \"markdown\",\n   \"metadata\": {},\n   \"source\": [\n    \"## Step 9: Summary and Next Steps\\n\",\n    \"\\n\",\n    \"Summarize what we've accomplished and prepare for the next phase.\"\n   ]\n  },\n  {\n   \"cell_type\": \"code\",\n   \"execution_count\": null,\n   \"metadata\": {},\n   \"outputs\": [],\n   \"source\": [\n    \"# Final summary\\n\",\n    \"cat(\\\"\\\\n\\\")\\n\",\n    \"cat(\\\"===========================================\\\\n\\\")\\n\",\n    \"cat(\\\"🎯 TRAJETORIAS DATA COLLECTION COMPLETE! \\\\n\\\")\\n\",\n    \"cat(\\\"===========================================\\\\n\\\")\\n\",\n    \"\\n\",\n    \"# Count deliverables\\n\",\n    \"files_created <- list()\\n\",\n    \"\\n\",\n    \"# Check for processed files\\n\",\n    \"processed_files <- list.files(\\\"data/processed\\\", pattern = \\\"trajetorias_.*_amazon.csv\\\", full.names = FALSE)\\n\",\n    \"files_created$processed_components <- length(processed_files)\\n\",\n    \"\\n\",\n    \"# Check for key indicator files\\n\",\n    \"key_files <- list.files(\\\"data/processed\\\", pattern = \\\"key_indicators_.*\\\\.csv\\\", full.names = FALSE)\\n\",\n    \"files_created$key_indicator_files <- length(key_files)\\n\",\n    \"\\n\",\n    \"# Check for quality report\\n\",\n    \"quality_file_exists <- file.exists(\\\"quality_checks/trajetorias_quality_report.json\\\")\\n\",\n    \"files_created$quality_report <- quality_file_exists\\n\",\n    \"\\n\",\n    \"# Check for summary table\\n\",\n    \"summary_file_exists <- file.exists(\\\"outputs/tables/trajetorias_variable_summary.csv\\\")\\n\",\n    \"files_created$summary_table <- summary_file_exists\\n\",\n    \"\\n\",\n    \"cat(\\\"📋 Deliverables:\\\\n\\\")\\n\",\n    \"cat(\\\"   📊 Processed components:\\\", files_created$processed_components, \\\"\\\\n\\\")\\n\",\n    \"cat(\\\"   🎯 Key indicator files:\\\", files_created$key_indicator_files, \\\"\\\\n\\\")\\n\",\n    \"cat(\\\"   📋 Quality report:\\\", ifelse(files_created$quality_report, \\\"✅\\\", \\\"❌\\\"), \\\"\\\\n\\\")\\n\",\n    \"cat(\\\"   📈 Variable summary:\\\", ifelse(files_created$summary_table, \\\"✅\\\", \\\"❌\\\"), \\\"\\\\n\\\")\\n\",\n    \"\\n\",\n    \"# Data coverage summary\\n\",\n    \"if (length(processed_trajetorias) > 0) {\\n\",\n    \"  total_components <- length(processed_trajetorias)\\n\",\n    \"  \\n\",\n    \"  cat(\\\"\\\\n🌿 Data Coverage Summary:\\\\n\\\")\\n\",\n    \"  \\n\",\n    \"  for (component in names(processed_trajetorias)) {\\n\",\n    \"    data <- processed_trajetorias[[component]]\\n\",\n    \"    if (!is.null(data)) {\\n\",\n    \"      cat(\\\"   \\\", stringr::str_to_title(component), \\\":\\\", nrow(data), \\\"records\\\")\\n\",\n    \"      \\n\",\n    \"      if (\\\"abbrev_state\\\" %in% names(data)) {\\n\",\n    \"        states_covered <- length(unique(data$abbrev_state))\\n\",\n    \"        cat(\\\" |\\\", states_covered, \\\"states\\\")\\n\",\n    \"      }\\n\",\n    \"      \\n\",\n    \"      if (\\\"code_muni\\\" %in% names(data)) {\\n\",\n    \"        munis_covered <- length(unique(data$code_muni))\\n\",\n    \"        cat(\\\" |\\\", munis_covered, \\\"municipalities\\\")\\n\",\n    \"      }\\n\",\n    \"      \\n\",\n    \"      cat(\\\"\\\\n\\\")\\n\",\n    \"    }\\n\",\n    \"  }\\n\",\n    \"  \\n\",\n    \"  # Most important indicators identified\\n\",\n    \"  if (length(key_indicators) > 0) {\\n\",\n    \"    cat(\\\"\\\\n🎯 Key Indicators Available:\\\\n\\\")\\n\",\n    \"    \\n\",\n    \"    for (component in names(key_indicators)) {\\n\",\n    \"      data <- key_indicators[[component]]\\n\",\n    \"      if (!is.null(data)) {\\n\",\n    \"        exclude_cols <- c(\\\"code_muni\\\", \\\"year\\\", \\\"abbrev_state\\\", \\\"name_muni\\\")\\n\",\n    \"        indicator_count <- sum(!names(data) %in% exclude_cols)\\n\",\n    \"        cat(\\\"   \\\", stringr::str_to_title(component), \\\":\\\", indicator_count, \\\"indicators\\\\n\\\")\\n\",\n    \"      }\\n\",\n    \"    }\\n\",\n    \"  }\\n\",\n    \"  \\n\",\n    \"} else {\\n\",\n    \"  cat(\\\"⚠️ No processed data available\\\\n\\\")\\n\",\n    \"}\\n\",\n    \"\\n\",\n    \"cat(\\\"\\\\n🔗 Integration Readiness:\\\\n\\\")\\n\",\n    \"cat(\\\"   📊 Census data:\\\", ifelse(file.exists(\\\"data/raw/census/amazon_population_2022.csv\\\"), \\\"✅ Ready\\\", \\\"❌ Missing\\\"), \\\"\\\\n\\\")\\n\",\n    \"cat(\\\"   🌿 Trajetorias data:\\\", ifelse(length(processed_trajetorias) > 0, \\\"✅ Ready\\\", \\\"❌ Missing\\\"), \\\"\\\\n\\\")\\n\",\n    \"cat(\\\"   🔥 Fire data:\\\", ifelse(file.exists(\\\"data/processed/amazon_fire_by_municipality.csv\\\"), \\\"✅ Ready\\\", \\\"⏳ Next step\\\"), \\\"\\\\n\\\")\\n\",\n    \"\\n\",\n    \"cat(\\\"\\\\n📚 Ready for next phase!\\\\n\\\")\\n\",\n    \"cat(\\\"▶️ Next: Open 04_fire_data.ipynb\\\\n\\\")\"\n   ]\n  },\n  {\n   \"cell_type\": \"markdown\",\n   \"metadata\": {},\n   \"source\": [\n    \"---\\n\",\n    \"\\n\",\n    \"## 📋 Checklist\\n\",\n    \"\\n\",\n    \"Before proceeding to the next notebook, verify:\\n\",\n    \"\\n\",\n    \"- [ ] Trajetorias dataset files downloaded successfully\\n\",\n    \"- [ ] Data filtered for Amazon region\\n\",\n    \"- [ ] Key indicators extracted for each component\\n\",\n    \"- [ ] Quality assessment completed\\n\",\n    \"- [ ] Summary visualizations created\\n\",\n    \"- [ ] Variable summary table generated\\n\",\n    \"\\n\",\n    \"## 🚨 Troubleshooting\\n\",\n    \"\\n\",\n    \"**If downloads fail:**\\n\",\n    \"- Check internet connection\\n\",\n    \"- Zenodo server may be temporarily unavailable\\n\",\n    \"- Try downloading individual files manually from Zenodo\\n\",\n    \"- Large files may take several minutes to download\\n\",\n    \"\\n\",\n    \"**If no Amazon municipalities found:**\\n\",\n    \"- Ensure census data was downloaded in previous step\\n\",\n    \"- Check that municipal codes are standardized correctly\\n\",\n    \"- Some components may not have complete Amazon coverage\\n\",\n    \"\\n\",\n    \"**If variables don't match expected names:**\\n\",\n    \"- Variable names may differ from expectations\\n\",\n    \"- Check the metadata files for actual variable names\\n\",\n    \"- The key variable extraction uses partial matching\\n\",\n    \"\\n\",\n    \"**If visualizations fail:**\\n\",\n    \"- May be due to non-numeric data or extreme outliers\\n\",\n    \"- Check for sufficient non-missing data\\n\",\n    \"- Some variables may need transformation before plotting\\n\",\n    \"\\n\",\n    \"---\\n\",\n    \"\\n\",\n    \"**📊 Files Created:**\\n\",\n    \"- `data/processed/trajetorias_*_amazon.csv` - Processed components for Amazon region\\n\",\n    \"- `data/processed/key_indicators_*.csv` - Key variables for PM2.5 analysis\\n\",\n    \"- `quality_checks/trajetorias_quality_report.json` - Data quality assessment\\n\",\n    \"- `outputs/tables/trajetorias_variable_summary.csv` - Complete variable summary\\n\",\n    \"\\n\",\n    \"**📈 Next Steps:**\\n\",\n    \"1. **04_fire_data.ipynb** - Process MapBiomas fire data\\n\",\n    \"2. **05_data_integration.ipynb** - Combine all datasets\\n\",\n    \"3. **06_quality_checks.ipynb** - Comprehensive quality assessment\\n\",\n    \"\\n\",\n    \"**🔍 Key Variables for PM2.5 Analysis:**\\n\",\n    \"- **Socioeconomic**: Multidimensional Poverty Index, income, education\\n\",\n    \"- **Health**: Vector-borne diseases (malaria, dengue), respiratory conditions\\n\",\n    \"- **Environmental**: Deforestation, land use, climate indicators\\n\",\n    \"- **Population**: Density, urbanization, migration patterns\"\n   ]\n  }\n ],\n \"metadata\": {\n  \"kernelspec\": {\n   \"display_name\": \"R\",\n   \"language\": \"R\",\n   \"name\": \"ir\"\n  },\n  \"language_info\": {\n   \"name\": \"R\"\n  }\n },\n \"nbformat\": 4,\n \"nbformat_minor\": 4\n},
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 1: Load Configuration and Libraries"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load essential libraries\n",
    "library(httr)\n",
    "library(jsonlite)\n",
    "library(readr)\n",
    "library(dplyr)\n",
    "library(ggplot2)\n",
    "library(DT)\n",
    "library(knitr)\n",
    "\n",
    "# Load project configuration if available\n",
    "if (file.exists(\"data/project_config.rds\")) {\n",
    "  config <- readRDS(\"data/project_config.rds\")\n",
    "  amazon_states <- config$amazon_states\n",
    "  cat(\"✅ Configuration loaded successfully\\n\")\n",
    "} else {\n",
    "  # Fallback - define Amazon states\n",
    "  amazon_states <- c(\"AC\", \"AP\", \"AM\", \"MA\", \"MT\", \"PA\", \"RO\", \"RR\", \"TO\")\n",
    "  cat(\"⚠️ Using fallback configuration\\n\")\n",
    "}\n",
    "\n",
    "# Helper functions\n",
    "standardize_muni_code <- function(code) {\n",
    "  sprintf(\"%07d\", as.numeric(code))\n",
    "}\n",
    "\n",
    "save_data_with_metadata <- function(data, filename, description = \"\") {\n",
    "  dir.create(dirname(filename), recursive = TRUE, showWarnings = FALSE)\n",
    "  write_csv(data, filename)\n",
    "  \n",
    "  metadata <- list(\n",
    "    filename = basename(filename),\n",
    "    created = Sys.time(),\n",
    "    rows = nrow(data),\n",
    "    columns = ncol(data),\n",
    "    description = description\n",
    "  )\n",
    "  \n",
    "  metadata_file <- paste0(tools::file_path_sans_ext(filename), \"_metadata.json\")\n",
    "  write(jsonlite::toJSON(metadata, pretty = TRUE), metadata_file)\n",
    "  cat(\"💾 Saved:\", filename, \"(\", nrow(data), \"rows)\\n\")\n",
    "}\n",
    "\n",
    "cat(\"📚 Libraries loaded and helper functions defined\\n\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 2: Download Trajetorias Dataset Files\n",
    "\n",
    "The Trajetorias dataset contains 4 main indicator files plus metadata."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Define Zenodo URLs for Trajetorias dataset\n",
    "cat(\"🌐 Preparing to download Trajetorias dataset...\\n\")\n",
    "\n",
    "base_url <- \"https://zenodo.org/records/7098053/files/\"\n",
    "\n",
    "# Main data files\n",
    "trajetorias_urls <- list(\n",
    "  population = paste0(base_url, \"TRAJETORIAS_DATASET_Population_indicators.csv\"),\n",
    "  socioeconomic = paste0(base_url, \"TRAJETORIAS_DATASET_Socio-Economic_dimension-indicators.csv\"),\n",
    "  epidemiological = paste0(base_url, \"TRAJETORIAS_DATASET_Epidemiological_dimension_indicators.csv\"),\n",
    "  environmental = paste0(base_url, \"TRAJETORIAS_DATASET_Environmental_dimension_indicators.csv\")\n",
    ")\n",
    "\n",
    "# Metadata files\n",
    "metadata_urls <- list(\n",
    "  population_meta = paste0(base_url, \"TRAJETORIAS_DATASET_Population_indicators_METADATA.csv\"),\n",
    "  socioeconomic_meta = paste0(base_url, \"TRAJETORIAS_DATASET_Socio-Economic_dimension-indicators_METADATA.csv\"),\n",
    "  epidemiological_meta = paste0(base_url, \"TRAJETORIAS_DATASET_Epidemiological_dimension_indicators_METADATA.csv\"),\n",
    "  environmental_meta = paste0(base_url, \"TRAJETORIAS_DATASET_Environmental_dimension_indicators_METADATA.csv\")\n",
    ")\n",
    "\n",
    "cat(\"📋 Dataset components identified:\\n\")\n",
    "cat(\"   - Population indicators\\n\")\n",
    "cat(\"   - Socio-economic indicators\\n\")\n",
    "cat(\"   - Epidemiological indicators\\n\")\n",
    "cat(\"   - Environmental indicators\\n\")\n",
    "cat(\"   - Metadata for each component\\n\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Function to download files from Zenodo\n",
    "download_trajetorias_file <- function(url, filename) {\n",
    "  cat(\"⬇️ Downloading:\", filename, \"...\")\n",
    "  \n",
    "  tryCatch({\n",
    "    # Create directory if it doesn't exist\n",
    "    dir.create(dirname(filename), recursive = TRUE, showWarnings = FALSE)\n",
    "    \n",
    "    # Download file\n",
    "    response <- GET(url, timeout(300))  # 5 minute timeout\n",
    "    \n",
    "    if (status_code(response) == 200) {\n",
    "      # Save file\n",
    "      writeBin(content(response, \"raw\"), filename)\n",
    "      \n",
    "      # Check file size\n",
    "      file_size <- file.info(filename)$size\n",
    "      cat(\" ✅ Success (\", round(file_size/1024/1024, 1), \"MB)\\n\")\n",
    "      return(TRUE)\n",
    "    } else {\n",
    "      cat(\" ❌ Failed (HTTP\", status_code(response), \")\\n\")\n",
    "      return(FALSE)\n",
    "    }\n",
    "    \n",
    "  }, error = function(e) {\n",
    "    cat(\" ❌ Error:\", e$message, \"\\n\")\n",
    "    return(FALSE)\n",
    "  })\n",
    "}\n",
    "\n",
    "# Download main data files\n",
    "cat(\"\\n📥 Downloading main dataset files...\\n\")\n",
    "download_success <- list()\n",
    "\n",
    "for (name in names(trajetorias_urls)) {\n",
    "  filename <- paste0(\"data/raw/trajetorias/\", name, \"_indicators.csv\")\n",
    "  download_success[[name]] <- download_trajetorias_file(trajetorias_urls[[name]], filename)\n",
    "}\n",
    "\n",
    "# Download metadata files\n",
    "cat(\"\\n📋 Downloading metadata files...\\n\")\n",
    "for (name in names(metadata_urls)) {\n",
    "  filename <- paste0(\"data/raw/trajetorias/\", name, \".csv\")\n",
    "  download_trajetorias_file(metadata_urls[[name]], filename)\n",
    "}\n",
    "\n",
    "# Summary of downloads\n",
    "successful_downloads <- sum(unlist(download_success))\n",
    "total_downloads <- length(download_success)\n",
    "\n",
    "cat(\"\\n📊 Download Summary:\\n\")\n",
    "cat(\"   Successful:\", successful_downloads, \"/\", total_downloads, \"main files\\n\")\n",
    "\n",
    "if (successful_downloads == total_downloads) {\n",
    "  cat(\"✅ All downloads completed successfully!\\n\")\n",
    "} else {\n",
    "  cat(\"⚠️ Some downloads failed. Proceeding with available data...\\n\")\n",
    "}"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 3: Load and Explore Dataset Structure\n",
    "\n",
    "Examine each component of the Trajetorias dataset to understand what data is available."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Function to load and explore Trajetorias data\n",
    "explore_trajetorias_component <- function(component_name) {\n",
    "  filename <- paste0(\"data/raw/trajetorias/\", component_name, \"_indicators.csv\")\n",
    "  \n",
    "  if (!file.exists(filename)) {\n",
    "    cat(\"❌\", component_name, \"file not found\\n\")\n",
    "    return(NULL)\n",
    "  }\n",
    "  \n",
    "  cat(\"\\n=== \", toupper(component_name), \" COMPONENT ===\\n\")\n",
    "  \n",
    "  # Load data\n",
    "  tryCatch({\n",
    "    data <- read_csv(filename, show_col_types = FALSE)\n",
    "    \n",
    "    # Basic information\n",
    "    cat(\"📊 Dimensions:\", nrow(data), \"rows ×\", ncol(data), \"columns\\n\")\n",
    "    \n",
    "    # Check for key columns\n",
    "    if (\"code_muni\" %in% names(data)) {\n",
    "      cat(\"🏘️ Municipalities:\", length(unique(data$code_muni)), \"\\n\")\n",
    "    }\n",
    "    \n",
    "    if (\"year\" %in% names(data)) {\n",
    "      years <- sort(unique(data$year))\n",
    "      cat(\"📅 Years available:\", paste(years, collapse = \", \"), \"\\n\")\n",
    "    }\n",
    "    \n",
    "    # Show column names (first 10)\n",
    "    cat(\"📋 Columns (first 10):\\n\")\n",
    "    col_preview <- head(names(data), 10)\n",
    "    for (col in col_preview) {\n",
    "      cat(\"   -\", col, \"\\n\")\n",
    "    }\n",
    "    \n",
    "    if (ncol(data) > 10) {\n",
    "      cat(\"   ... and\", ncol(data) - 10, \"more columns\\n\")\n",
    "    }\n",
    "    \n",
    "    # Check for Amazon municipalities if code_muni exists\n",
    "    if (\"code_muni\" %in% names(data)) {\n",
    "      # Standardize codes\n",
    "      data$code_muni <- standardize_muni_code(data$code_muni)\n",
    "      \n",
    "      # Check coverage - we'll need to merge with census data to get state info\n",
    "      cat(\"🔍 Municipal codes standardized\\n\")\n",
    "    }\n",
    "    \n",
    "    return(data)\n",
    "    \n",
    "  }, error = function(e) {\n",
    "    cat(\"❌ Error loading\", component_name, \":\", e$message, \"\\n\")\n",
    "    return(NULL)\n",
    "  })\n",
    "}\n",
    "\n",
    "# Explore each component\n",
    "trajetorias_data <- list()\n",
    "components <- c(\"population\", \"socioeconomic\", \"epidemiological\", \"environmental\")\n",
    "\n",
    "for (component in components) {\n",
    "  trajetorias_data[[component]] <- explore_trajetorias_component(component)\n",
    "}"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 4: Filter for Amazon Region and Recent Years\n",
    "\n",
    "Extract the most relevant data for our Amazon analysis."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load census data to get state mappings\n",
    "cat(\"🗺️ Loading municipality-state mappings...\\n\")\n",
    "\n",
    "# Try to load census data for state mapping\n",
    "state_mapping <- NULL\n",
    "if (file.exists(\"data/raw/census/amazon_population_2022.csv\")) {\n",
    "  census_data <- read_csv(\"data/raw/census/amazon_population_2022.csv\", show_col_types = FALSE)\n",
    "  state_mapping <- census_data %>% \n",
    "    select(code_muni, abbrev_state, name_muni) %>%\n",
    "    mutate(code_muni = standardize_muni_code(code_muni))\n",
    "  \n",
    "  cat(\"✅ Loaded state mapping for\", nrow(state_mapping), \"Amazon municipalities\\n\")\n",
    "} else {\n",
    "  cat(\"⚠️ Census data not available. Will process all municipalities.\\n\")\n",
    "}\n",
    "\n",
    "# Function to process and filter Trajetorias component\n",
    "process_trajetorias_component <- function(data, component_name, state_mapping = NULL) {\n",
    "  if (is.null(data)) {\n",
    "    cat(\"⚠️ No data available for\", component_name, \"\\n\")\n",
    "    return(NULL)\n",
    "  }\n",
    "  \n",
    "  cat(\"\\n🔄 Processing\", component_name, \"component...\\n\")\n",
    "  \n",
    "  # Standardize municipal codes\n",
    "  if (\"code_muni\" %in% names(data)) {\n",
    "    data$code_muni <- standardize_muni_code(data$code_muni)\n",
    "  }\n",
    "  \n",
    "  # Filter for Amazon municipalities if we have state mapping\n",
    "  if (!is.null(state_mapping) && \"code_muni\" %in% names(data)) {\n",
    "    amazon_munis <- state_mapping$code_muni\n",
    "    data_amazon <- data %>% filter(code_muni %in% amazon_munis)\n",
    "    \n",
    "    cat(\"🌿 Filtered to\", nrow(data_amazon), \"Amazon municipality records\\n\")\n",
    "    data <- data_amazon\n",
    "  }\n",
    "  \n",
    "  # Get most recent year if multiple years available\n",
    "  if (\"year\" %in% names(data)) {\n",
    "    latest_year <- max(data$year, na.rm = TRUE)\n",
    "    data_recent <- data %>% filter(year == latest_year)\n",
    "    \n",
    "    cat(\"📅 Using most recent year:\", latest_year, \"(\", nrow(data_recent), \"records)\\n\")\n",
    "    data <- data_recent\n",
    "  }\n",
    "  \n",
    "  # Add state information if available\n",
    "  if (!is.null(state_mapping) && \"code_muni\" %in% names(data)) {\n",
    "    data <- data %>% \n",
    "      left_join(state_mapping %>% select(code_muni, abbrev_state), \n",
    "                by = \"code_muni\")\n",
    "    cat(\"🏛️ Added state information\\n\")\n",
    "  }\n",
    "  \n",
    "  return(data)\n",
    "}\n",
    "\n",
    "# Process each component\n",
    "processed_trajetorias <- list()\n",
    "\n",
    "for (component in names(trajetorias_data)) {\n",
    "  processed_data <- process_trajetorias_component(\n",
    "    trajetorias_data[[component]], \n",
    "    component, \n",
    "    state_mapping\n",
    "  )\n",
    "  \n",
    "  if (!is.null(processed_data)) {\n",
    "    processed_trajetorias[[component]] <- processed_data\n",
    "    \n",
    "    # Save processed data\n",
    "    filename <- paste0(\"data/processed/trajetorias_\", component, \"_amazon.csv\")\n",
    "    save_data_with_metadata(\n",
    "      processed_data, \n",
    "      filename,\n",
    "      paste(\"Processed\", component, \"indicators from Trajetorias dataset for Amazon region\")\n",
    "    )\n",
    "  }\n",
    "}"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 5: Extract Key Variables\n",
    "\n",
    "Identify and extract the most important variables for our PM2.5 analysis."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Define key variables of interest for PM2.5 analysis\n",
    "cat(\"🎯 Identifying key variables for PM2.5 analysis...\\n\")\n",
    "\n",
    "key_variables <- list(\n",
    "  socioeconomic = c(\n",
    "    \"mpi_rural\", \"mpi_urban\", \"mpi_general\",  # Multidimensional Poverty Index\n",
    "    \"poverty_incidence\", \"poverty_intensity\",   # Poverty measures\n",
    "    \"income\", \"education\", \"employment\"          # Socioeconomic indicators\n",
    "  ),\n",
    "  epidemiological = c(\n",
    "    \"malaria\", \"dengue\", \"leishmaniasis\",        # Vector-borne diseases\n",
    "    \"respiratory\", \"diarrhea\",                   # Health indicators\n",
    "    \"health_access\", \"hospital_density\"          # Health system access\n",
    "  ),\n",
    "  environmental = c(\n",
    "    \"deforestation\", \"forest_cover\",             # Forest indicators\n",
    "    \"agriculture\", \"pasture\", \"urban_area\",      # Land use\n",
    "    \"precipitation\", \"temperature\",              # Climate\n",
    "    \"road_density\", \"mining\"                     # Infrastructure/extractive\n",
    "  ),\n",
    "  population = c(\n",
    "    \"population_density\", \"urban_population\",    # Population distribution\n",
    "    \"migration\", \"age_structure\"                 # Demographic characteristics\n",
    "  )\n",
    ")\n",
    "\n",
    "# Function to extract available key variables\n",
    "extract_key_variables <- function(data, component_name, key_vars) {\n",
    "  if (is.null(data)) return(NULL)\n",
    "  \n",
    "  cat(\"\\n🔍 Extracting key variables from\", component_name, \"...\\n\")\n",
    "  \n",
    "  # Get column names (case insensitive matching)\n",
    "  available_cols <- names(data)\n",
    "  \n",
    "  # Find variables that match our key variables (partial matching)\n",
    "  found_vars <- c()\n",
    "  for (key_var in key_vars) {\n",
    "    # Look for columns containing the key variable name\n",
    "    matches <- grep(key_var, available_cols, ignore.case = TRUE, value = TRUE)\n",
    "    if (length(matches) > 0) {\n",
    "      found_vars <- c(found_vars, matches[1])  # Take first match\n",
    "      cat(\"   ✅ Found:\", key_var, \"→\", matches[1], \"\\n\")\n",
    "    }\n",
    "  }\n",
    "  \n",
    "  # Always include essential columns\n",
    "  essential_cols <- c(\"code_muni\", \"year\", \"abbrev_state\")\n",
    "  essential_available <- essential_cols[essential_cols %in% available_cols]\n",
    "  \n",
    "  # Select found variables plus essential columns\n",
    "  selected_cols <- unique(c(essential_available, found_vars))\n",
    "  \n",
    "  if (length(found_vars) > 0) {\n",
    "    extracted_data <- data %>% select(all_of(selected_cols))\n",
    "    cat(\"📋 Extracted\", length(found_vars), \"key variables +\", length(essential_available), \"essential columns\\n\")\n",
    "    return(extracted_data)\n",
    "  } else {\n",
    "    cat(\"⚠️ No matching key variables found\\n\")\n",
    "    return(NULL)\n",
    "  }\n",
    "}\n",
    "\n",
    "# Extract key variables from each component\n",
    "key_indicators <- list()\n",
    "\n",
    "for (component in names(processed_trajetorias)) {\n",
    "  if (component %in% names(key_variables)) {\n",
    "    extracted <- extract_key_variables(\n",
    "      processed_trajetorias[[component]],\n",
    "      component,\n",
    "      key_variables[[component]]\n",
    "    )\n",
    "    \n",
    "    if (!is.null(extracted)) {\n",
    "      key_indicators[[component]] <- extracted\n",
    "      \n",
    "      # Save key indicators\n",
    "      filename <- paste0(\"data/processed/key_indicators_\", component, \".csv\")\n",
    "      save_data_with_metadata(\n",
    "        extracted,\n",
    "        filename,\n",
    "        paste(\"Key\", component, \"indicators for PM2.5 analysis\")\n",
    "      )\n",
    "    }\n",
    "  }\n",
    "}"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 6: Create Summary Visualizations\n",
    "\n",
    "Generate quick visualizations to understand the data patterns."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create summary visualizations\n",
    "cat(\"📊 Creating summary visualizations...\\n\")\n",
    "\n",
    "# Function to create summary plots\n",
    "create_summary_plots <- function(data, component_name) {\n",
    "  if (is.null(data) || nrow(data) == 0) {\n",
    "    cat(\"⚠️ No data available for\", component_name, \"plots\\n\")\n",
    "    return(NULL)\n",
    "  }\n",
    "  \n",
    "  cat(\"\\n📈 Creating plots for\", component_name, \"...\\n\")\n",
    "  \n",
    "  # Get numeric columns (excluding ID columns)\n",
    "  exclude_cols <- c(\"code_muni\", \"year\", \"abbrev_state\", \"name_muni\")\n",
    "  numeric_cols <- names(data)[sapply(data, is.numeric) & \n",
    "                              !names(data) %in% exclude_cols]\n",
    "  \n",
    "  if (length(numeric_cols) == 0) {\n",
    "    cat(\"   ⚠️ No numeric variables found\\n\")\n",
    "    return(NULL)\n",
    "  }\n",
    "  \n",
    "  # Take first few numeric variables for plotting\n",
    "  plot_vars <- head(numeric_cols, 4)\n",
    "  \n",
    "  plots <- list()\n",
    "  \n",
    "  for (var in plot_vars) {\n",
    "    tryCatch({\n",
    "      # Remove missing values\n",
    "      plot_data <- data[!is.na(data[[var]]), ]\n",
    "      \n",
    "      if (nrow(plot_data) > 0) {\n",
    "        # Histogram\n",
    "        p <- ggplot(plot_data, aes_string(x = var)) +\n",
    "          geom_histogram(bins = 20, fill = \"steelblue\", alpha = 0.7) +\n",
    "          labs(title = paste(\"Distribution of\", var),\n",
    "               subtitle = paste(component_name, \"component\"),\n",
    "               x = var, y = \"Count\") +\n",
    "          theme_minimal()\n",
    "        \n",
    "        print(p)\n",
    "        plots[[var]] <- p\n",
    "        \n",
    "        # Basic statistics\n",
    "        cat(\"   📊\", var, \":\", \n",
    "            \"Mean =\", round(mean(plot_data[[var]], na.rm = TRUE), 2),\n",
    "            \"| Median =\", round(median(plot_data[[var]], na.rm = TRUE), 2),\n",
    "            \"| Range =\", round(min(plot_data[[var]], na.rm = TRUE), 2), \"-\",\n",
    "            round(max(plot_data[[var]], na.rm = TRUE), 2), \"\\n\")\n",
    "      }\n",
    "    }, error = function(e) {\n",
    "      cat(\"   ⚠️ Could not plot\", var, \":\", e$message, \"\\n\")\n",
    "    })\n",
    "  }\n",
    "  \n",
    "  return(plots)\n",
    "}\n",
    "\n",
    "# Create plots for each component with key indicators\n",
    "summary_plots <- list()\n",
    "\n",
    "for (component in names(key_indicators)) {\n",
    "  plots <- create_summary_plots(key_indicators[[component]], component)\n",
    "  if (!is.null(plots)) {\n",
    "    summary_plots[[component]] <- plots\n",
    "  }\n",
    "}\n",
    "\n",
    "cat(\"\\n✅ Summary visualizations complete!\\n\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 7: Data Quality Assessment\n",
    "\n",
    "Assess the quality and completeness of the Trajetorias data."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Comprehensive quality assessment\n",
    "cat(\"🔍 Running Trajetorias data quality assessment...\\n\")\n",
    "\n",
    "quality_report <- list()\n",
    "\n",
    "# Assess each component\n",
    "for (component in names(processed_trajetorias)) {\n",
    "  data <- processed_trajetorias[[component]]\n",
    "  \n",
    "  if (!is.null(data)) {\n",
    "    \n",
    "    # Basic metrics\n",
    "    quality_metrics <- list(\n",
    "      total_records = nrow(data),\n",
    "      total_variables = ncol(data),\n",
    "      unique_municipalities = length(unique(data$code_muni)),\n",
    "      years_covered = if(\"year\" %in% names(data)) sort(unique(data$year)) else \"N/A\",\n",
    "      states_covered = if(\"abbrev_state\" %in% names(data)) length(unique(data$abbrev_state)) else \"N/A\"\n",
    "    )\n",
    "    \n",
    "    # Missing data analysis\n",
    "    missing_analysis <- data %>%\n",
    "      summarise_all(~sum(is.na(.))) %>%\n",
    "      gather(variable, missing_count) %>%\n",
    "      mutate(missing_percent = round((missing_count / nrow(data)) * 100, 1)) %>%\n",
    "      filter(missing_count > 0) %>%\n",
    "      arrange(desc(missing_count))\n",
    "    \n",
    "    quality_metrics$missing_data_summary <- list(\n",
    "      variables_with_missing = nrow(missing_analysis),\n",
    "      total_variables = ncol(data),\n",
    "      worst_missing_var = if(nrow(missing_analysis) > 0) missing_analysis$variable[1] else \"None\",\n",
    "      worst_missing_pct = if(nrow(missing_analysis) > 0) missing_analysis$missing_percent[1] else 0\n",
    "    )\n",
    "    \n",
    "    # Summary statistics for numeric variables\n",
    "    numeric_vars <- names(data)[sapply(data, is.numeric)]\n",
    "    if (length(numeric_vars) > 0) {\n",
    "      numeric_summary <- data %>%\n",
    "        select(all_of(numeric_vars)) %>%\n",
    "        summarise_all(list(\n",
    "          mean = ~mean(., na.rm = TRUE),\n",
    "          median = ~median(., na.rm = TRUE),\n",
    "          min = ~min(., na.rm = TRUE),\n",
    "          max = ~max(., na.rm = TRUE)\n",
    "        ), .groups = \"drop\")\n",
    "      \n",
    "      quality_metrics$numeric_variables = length(numeric_vars)\n",
    "    }\n",
    "    \n",
    "    quality_report[[component]] <- quality_metrics\n",
    "    \n",
    "    # Print key findings\n",
    "    cat(\"   📊 Records:\", quality_metrics$total_records, \"\\n\")\n",
    "    cat(\"   📋 Variables:\", quality_metrics$total_variables, \"\\n\")\n",
    "    cat(\"   🏘️ Municipalities:\", quality_metrics$unique_municipalities, \"\\n\")\n",
    "    \n",
    "    if (quality_metrics$years_covered != \"N/A\") {\n",
    "      years_str <- if(length(quality_metrics$years_covered) > 3) {\n",
    "        paste(min(quality_metrics$years_covered), \"-\", max(quality_metrics$years_covered))\n",
    "      } else {\n",
    "        paste(quality_metrics$years_covered, collapse = \", \")\n",
    "      }\n",
    "      cat(\"   📅 Years:\", years_str, \"\\n\")\n",
    "    }\n",
    "    \n",
    "    if (quality_metrics$states_covered != \"N/A\") {\n",
    "      cat(\"   🏛️ States:\", quality_metrics$states_covered, \"/\", length(amazon_states), \"\\n\")\n",
    "    }\n",
    "    \n",
    "    cat(\"   ❓ Variables with missing data:\", \n",
    "        quality_metrics$missing_data_summary$variables_with_missing, \"/\",\n",
    "        quality_metrics$missing_data_summary$total_variables, \"\\n\")\n",
    "    \n",
    "    if (quality_metrics$missing_data_summary$worst_missing_pct > 0) {\n",
    "      cat(\"   ⚠️ Highest missing data:\", \n",
    "          quality_metrics$missing_data_summary$worst_missing_var, \n",
    "          \"(\", quality_metrics$missing_data_summary$worst_missing_pct, \"%)\\n\")\n",
    "    }\n",
    "  }\n",
    "}\n",
    "\n",
    "# Overall assessment\n",
    "cat(\"\\n🎯 Overall Trajetorias Data Assessment:\\n\")\n",
    "total_components <- length(quality_report)\n",
    "components_with_data <- sum(sapply(quality_report, function(x) x$total_records > 0))\n",
    "\n",
    "cat(\"   📦 Components available:\", components_with_data, \"/\", length(trajetorias_urls), \"\\n\")\n",
    "\n",
    "if (components_with_data > 0) {\n",
    "  total_records <- sum(sapply(quality_report, function(x) x$total_records))\n",
    "  cat(\"   📊 Total records across components:\", total_records, \"\\n\")\n",
    "  \n",
    "  # Check municipality coverage\n",
    "  if (\"socioeconomic\" %in% names(quality_report)) {\n",
    "    muni_coverage <- quality_report$socioeconomic$unique_municipalities\n",
    "    if (!is.null(state_mapping)) {\n",
    "      total_amazon_munis <- nrow(state_mapping)\n",
    "      coverage_pct <- round((muni_coverage / total_amazon_munis) * 100, 1)\n",
    "      cat(\"   🌿 Amazon municipality coverage:\", muni_coverage, \"/\", \n",
    "          total_amazon_munis, \"(\", coverage_pct, \"%)\\n\")\n",
    "    }\n",
    "  }\n",
    "}\n",
    "\n",
    "# Save quality report\n",
    "write(jsonlite::toJSON(quality_report, pretty = TRUE), \n",
    "      \"quality_checks/trajetorias_quality_report.json\")\n",
    "\n",
    "cat(\"\\n💾 Quality report saved to quality_checks/trajetorias_quality_report.json\\n\")"\n
